#!/usr/bin/env bash
# =============================================================================
# generate-inventory.sh — Bridges Terraform outputs → Ansible inventory
# =============================================================================
# Run after `terraform apply` to auto-generate the Ansible inventory file
# from the live VM IPs.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="${PROJECT_DIR}/terraform"
INVENTORY_FILE="${PROJECT_DIR}/ansible/inventory/hosts.ini"

echo "==> Generating Ansible inventory from Terraform outputs..."

# Get IPs from Terraform
cd "$TERRAFORM_DIR"

WAZUH_EXTERNAL_IP=$(terraform output -raw wazuh_server_ip 2>/dev/null)
WAZUH_INTERNAL_IP=$(terraform output -raw wazuh_server_internal_ip 2>/dev/null)
SSH_USER=$(terraform output -raw ssh_user 2>/dev/null || echo "ubuntu")

# Get all external IPs as JSON and parse
VM_IPS_JSON=$(terraform output -json vm_external_ips 2>/dev/null)

AGENT_UBUNTU_IP=$(echo "$VM_IPS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['agent-ubuntu'])")
AGENT_ROCKY_IP=$(echo "$VM_IPS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['agent-rocky'])")
AGENT_DEBIAN_IP=$(echo "$VM_IPS_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['agent-debian'])")

# Validate we got all IPs
for var_name in WAZUH_EXTERNAL_IP WAZUH_INTERNAL_IP AGENT_UBUNTU_IP AGENT_ROCKY_IP AGENT_DEBIAN_IP; do
    if [[ -z "${!var_name}" ]]; then
        echo "ERROR: Failed to get ${var_name} from Terraform outputs."
        echo "Make sure 'terraform apply' has been run successfully."
        exit 1
    fi
done

# Generate inventory file
cat > "$INVENTORY_FILE" << EOF
# =============================================================================
# SIEM Lab — Ansible Inventory
# =============================================================================
# AUTO-GENERATED by scripts/generate-inventory.sh
# Generated at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Do not edit manually — run: make inventory
# =============================================================================

[wazuh_server]
wazuh-server ansible_host=${WAZUH_EXTERNAL_IP}

[agents]
agent-ubuntu ansible_host=${AGENT_UBUNTU_IP}
agent-rocky  ansible_host=${AGENT_ROCKY_IP}
agent-debian ansible_host=${AGENT_DEBIAN_IP}

[agents:vars]
wazuh_manager_ip=${WAZUH_INTERNAL_IP}

[all:vars]
ansible_user=${SSH_USER}
ansible_ssh_private_key_file=~/.ssh/gcp_key
ansible_python_interpreter=/usr/bin/python3
EOF

echo "==> Inventory generated at: ${INVENTORY_FILE}"
echo ""
echo "    Wazuh Server:  ${WAZUH_EXTERNAL_IP} (internal: ${WAZUH_INTERNAL_IP})"
echo "    Agent Ubuntu:  ${AGENT_UBUNTU_IP}"
echo "    Agent Rocky:   ${AGENT_ROCKY_IP}"
echo "    Agent Debian:  ${AGENT_DEBIAN_IP}"
echo ""
echo "==> Next: cd ansible && ansible-playbook site.yml"
